### ISSUE TITLE
ImportError: PyQt4, PyQt5, PySide or PySide2 are not available for import

### ISSUE THREAD

**Issue by bartonhammond** [UmSenhorQualquer/pyforms-gui#9]
On Mac 10.14.4

I installed `pip install pyforms-gui`
I created the `example.py` file
Am trying the `ComputerVisionAlgorithm` example
```
pyforms $ python example.py 
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from pyforms.basewidget import BaseWidget
  File "/usr/local/lib/python2.7/site-packages/pyforms/__init__.py", line 26, in <module>
    from pyforms_gui.appmanager import start_app
  File "/usr/local/lib/python2.7/site-packages/pyforms_gui/appmanager.py", line 3, in <module>
    from pyforms_gui.controls.control_dockwidget import ControlDockWidget
  File "/usr/local/lib/python2.7/site-packages/pyforms_gui/controls/control_dockwidget.py", line 4, in <module>
    from pyforms_gui.controls.control_emptywidget import ControlEmptyWidget
  File "/usr/local/lib/python2.7/site-packages/pyforms_gui/controls/control_emptywidget.py", line 6, in <module>
    from AnyQt                              import _api
  File "/usr/local/lib/python2.7/site-packages/AnyQt/_api.py", line 100, in <module>
    raise ImportError("PyQt4, PyQt5, PySide or PySide2 are not available for import")
ImportError: PyQt4, PyQt5, PySide or PySide2 are not available for import
```

**Comment by bartonhammond** [comment]
I switched to `conda` env and then `pip install pyforms-gui` and the example now runs.
